- name: proxmox
  hosts: all
  vars_files:
    - ../variables/lazy.yml
  tasks:
    - set_fact:
        yeppers: "ubuntu-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    - proxmox_kvm:
        api_user    : root@pam
        api_password: "{{ password }}"
        api_host    : pve
        clone       : ubuntu-20gb   # The VM source
        name        : "{{ yeppers }}"  # The target VM name
        node        : pve
        storage     : nvme
        format      : raw
        timeout     : 500  # Note: The task can take a while. Adapt
    - name: start vm
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ password }}"
        api_host: pve
        name: "{{ yeppers }}"
        node: pve
        state: started
    - name: firststuff
      shell: qm list | grep "{{ yeppers }}" | awk '{ print $1 }'
      register: thevmid
    - name: debug
      debug:
        var: thevmid.stdout 
    - name: getstuff
      shell: qm config "{{ thevmid.stdout }}" | grep ^net0 | awk -F, '{print $1}' | awk -F= '{print $2}'
      register: stuff
    - name: debug
      debug:
        var: stuff.stdout
    - name: wait
      ansible.builtin.pause:
        seconds: 20
    - name: getarp
      shell: nmap -sn 10.0.0.0/24
      register: nmap
    - name: debug
      debug:
        var: nmap.stdout_lines
    - name: Execute bun script
      command:
        cmd: bun get-vm/test.js "{{ stuff.stdout }}" "{{ nmap.stdout_lines | join('##')}}"
      register: script_output
    - name: Display script output
      debug:
        var: script_output.stdout
    - name: discord Notification
      community.general.discord:
        webhook_id: "{{ webhook_id }}"
        webhook_token: "{{ webhook_token }}"
        content: |
          ### Your Server is READY!! ###
          --------------------------------------
          ``
          `Server`: "{{ yeppers }}"
          `IP ADDRESS`: "{{ script_output.stdout}}"
          'URL': ssh://root@{{ script_output.stdout }}
          --------------------------------------
      ignore_errors: true
