- hosts: proxmox
  become: yes
  vars_files:
    - ../variables/proxmox_kvm.yml
    
  tasks:
    - name: Create vm id "{{ new_machine_id }}, {{ machine }}"
      community.general.proxmox_kvm:
        node: "{{ prox_node }}"
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: "{{ prox_node }}"
        name: "{{ machine }}"
        newid: "{{ new_machine_id }}"
        clone: "{{ clone }}"
        storage: "{{ storage }}"
        format: raw
        timeout: 300
        
    - name: update vm "{{ new_machine_id }} , {{ machine }}"
      community.general.proxmox_kvm:
        node: "{{ prox_node }}"
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: "{{ prox_node }}"
        name: "{{ machine }}"
        ipconfig:
          ipconfig0: '{{ ip }}/24,{{ router }}'
        update: true

    - name: Start container
      community.general.proxmox_kvm:
        vmid: "{{ new_machine_id }}"
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: "{{ prox_node }}"
        state: "{{ state }}"

        