- hosts: proxmox
  become: yes
  tasks:
    - name: Create vm id "{{ new_machine_id }}, {{ machine }}"
      community.general.proxmox_kvm:
        node: pve
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: pve
        name: "{{ machine }}"
        newid: "{{ new_machine_id }}"
        clone: ubuntu-20gb
        storage: nvme
        format: raw
        timeout: 300
        
    - name: update vm "{{ new_machine_id }} , {{ machine }}"
      community.general.proxmox_kvm:
        node: pve
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: pve
        name: "{{ machine }}"
        ipconfig:
          ipconfig0: '{{ ip }}/24,{{ router }}'
        update: true

    - name: Start container
      community.general.proxmox_kvm:
        vmid: "{{ new_machine_id }}"
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: pve
        state: "{{ state }}"


        